import 'dart:async';

import '../models/search_media_item.dart';

class MockSearchRepository {
  MockSearchRepository({List<SearchMediaItem>? items}) : _items = items ?? mockSearchItems;

  final List<SearchMediaItem> _items;

  Future<List<SearchMediaItem>> search({
    required String query,
    required SearchLanguageFilter language,
    required SearchMediaTypeFilter mediaType,
    required SearchSortOption sort,
  }) async {
    await Future<void>.delayed(const Duration(milliseconds: 650));

    final normalizedQuery = query.trim().toLowerCase();
    if (normalizedQuery == 'error' || normalizedQuery == '__error__') {
      throw StateError('Mock search failed.');
    }

    var results = _items.where((item) {
      final matchesQuery = normalizedQuery.isEmpty || item.title.toLowerCase().contains(normalizedQuery);
      final matchesLanguage = language == SearchLanguageFilter.all || item.language == language;
      final matchesMediaType = mediaType == SearchMediaTypeFilter.all || item.mediaType == mediaType;
      return matchesQuery && matchesLanguage && matchesMediaType;
    }).toList(growable: false);

    switch (sort) {
      case SearchSortOption.defaultOrder:
        break;
      case SearchSortOption.title:
        results = results.toList()
          ..sort((left, right) => left.title.toLowerCase().compareTo(right.title.toLowerCase()));
        break;
      case SearchSortOption.year:
        results = results.toList()..sort((left, right) => right.year.compareTo(left.year));
        break;
      case SearchSortOption.rating:
        results = results.toList()..sort((left, right) => right.rating.compareTo(left.rating));
        break;
    }

    return results;
  }
}

final List<SearchMediaItem> mockSearchItems = [
  SearchMediaItem(
    id: 'blackout-city',
    title: 'Blackout City',
    year: 2026,
    rating: 8.6,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Netflix',
    genres: ['Action', 'Sci-Fi'],
    posterLabel: 'Blackout City',
    overview: 'A courier crosses a neon city with a stolen memory vault.',
    runtimeLabel: '2h 18m',
  ),
  SearchMediaItem(
    id: 'signal-lost',
    title: 'Signal Lost',
    year: 2026,
    rating: 8.4,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Prime Video',
    genres: ['Drama', 'Action'],
    posterLabel: 'Signal Lost',
    overview: 'An ex-operator uncovers a hidden broadcast network.',
    runtimeLabel: '1h 56m',
  ),
  SearchMediaItem(
    id: 'midnight-harbor',
    title: 'Midnight Harbor',
    year: 2025,
    rating: 7.9,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Disney+',
    genres: ['Thriller', 'Mystery'],
    posterLabel: 'Midnight Harbor',
    overview: 'Harbor police investigate a missing cargo ship.',
    runtimeLabel: '2h 04m',
  ),
  SearchMediaItem(
    id: 'zero-day',
    title: 'Zero Day',
    year: 2026,
    rating: 8.1,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Apple TV',
    genres: ['Sci-Fi', 'Action'],
    posterLabel: 'Zero Day',
    overview: 'A systems engineer faces a city-wide collapse timeline.',
    runtimeLabel: '2h 10m',
  ),
  SearchMediaItem(
    id: 'glass-orbit',
    title: 'Glass Orbit',
    year: 2024,
    rating: 7.5,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Hulu',
    genres: ['Adventure', 'Sci-Fi'],
    posterLabel: 'Glass Orbit',
    overview: 'A salvage crew finds an impossible ring around Earth.',
    runtimeLabel: '1h 48m',
  ),
  SearchMediaItem(
    id: 'cold-front',
    title: 'Cold Front',
    year: 2025,
    rating: 8.0,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Plex',
    genres: ['Crime', 'Thriller'],
    posterLabel: 'Cold Front',
    overview: 'Two detectives track a winter smuggling route.',
    runtimeLabel: '2h 02m',
  ),
  SearchMediaItem(
    id: 'northbound',
    title: 'Northbound',
    year: 2024,
    rating: 7.7,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'YouTube',
    genres: ['Adventure', 'Drama'],
    posterLabel: 'Northbound',
    overview: 'A family drives north chasing a vanished radio signal.',
    runtimeLabel: '1h 51m',
  ),
  SearchMediaItem(
    id: 'night-protocol',
    title: 'Night Protocol',
    year: 2026,
    rating: 8.5,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Netflix',
    genres: ['Crime', 'TV'],
    posterLabel: 'Night Protocol',
    overview: 'A covert team manages incidents after midnight.',
    runtimeLabel: '48m',
  ),
  SearchMediaItem(
    id: 'halo-signal',
    title: 'Halo Signal',
    year: 2025,
    rating: 8.0,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Prime Video',
    genres: ['Sci-Fi', 'TV'],
    posterLabel: 'Halo Signal',
    overview: 'A rescue broadcast keeps returning from deep space.',
    runtimeLabel: '42m',
  ),
  SearchMediaItem(
    id: 'archive-west',
    title: 'Archive West',
    year: 2024,
    rating: 7.8,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Disney+',
    genres: ['Drama', 'TV'],
    posterLabel: 'Archive West',
    overview: 'Archivists uncover the truth behind a closed frontier city.',
    runtimeLabel: '44m',
  ),
  SearchMediaItem(
    id: 'after-hours',
    title: 'After Hours',
    year: 2026,
    rating: 8.2,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Apple TV',
    genres: ['Comedy', 'TV'],
    posterLabel: 'After Hours',
    overview: 'A late-night studio team keeps the city awake.',
    runtimeLabel: '33m',
  ),
  SearchMediaItem(
    id: 'signal-house',
    title: 'Signal House',
    year: 2025,
    rating: 7.6,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Hulu',
    genres: ['Thriller', 'TV'],
    posterLabel: 'Signal House',
    overview: 'A household appears on a broadcast from inside its walls.',
    runtimeLabel: '45m',
  ),
  SearchMediaItem(
    id: 'lunar-grid',
    title: 'Lunar Grid',
    year: 2024,
    rating: 8.1,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Plex',
    genres: ['Action', 'TV'],
    posterLabel: 'Lunar Grid',
    overview: 'Operators maintain a moon relay grid under pressure.',
    runtimeLabel: '40m',
  ),
  SearchMediaItem(
    id: 'sky-forge',
    title: 'Sky Forge',
    year: 2026,
    rating: 9.0,
    language: SearchLanguageFilter.japanese,
    mediaType: SearchMediaTypeFilter.anime,
    provider: 'Crunchyroll',
    genres: ['Action', 'Anime'],
    posterLabel: 'Sky Forge',
    overview: 'Sky pilots forge weapons from storm metal.',
    runtimeLabel: '24m',
  ),
  SearchMediaItem(
    id: 'violet-loop',
    title: 'Violet Loop',
    year: 2025,
    rating: 8.7,
    language: SearchLanguageFilter.japanese,
    mediaType: SearchMediaTypeFilter.anime,
    provider: 'Crunchyroll',
    genres: ['Sci-Fi', 'Anime'],
    posterLabel: 'Violet Loop',
    overview: 'A time loop binds a pilot to a violet sky station.',
    runtimeLabel: '24m',
  ),
  SearchMediaItem(
    id: 'redline-bloom',
    title: 'Redline Bloom',
    year: 2024,
    rating: 8.5,
    language: SearchLanguageFilter.japanese,
    mediaType: SearchMediaTypeFilter.anime,
    provider: 'Netflix',
    genres: ['Adventure', 'Anime'],
    posterLabel: 'Redline Bloom',
    overview: 'Racers cross a city as a mechanical garden wakes up.',
    runtimeLabel: '23m',
  ),
  SearchMediaItem(
    id: 'echo-garden',
    title: 'Echo Garden',
    year: 2026,
    rating: 8.3,
    language: SearchLanguageFilter.japanese,
    mediaType: SearchMediaTypeFilter.anime,
    provider: 'Disney+',
    genres: ['Fantasy', 'Anime'],
    posterLabel: 'Echo Garden',
    overview: 'A quiet garden echoes the voices of lost travelers.',
    runtimeLabel: '22m',
  ),
  SearchMediaItem(
    id: 'nova-tides',
    title: 'Nova Tides',
    year: 2024,
    rating: 8.2,
    language: SearchLanguageFilter.japanese,
    mediaType: SearchMediaTypeFilter.anime,
    provider: 'Apple TV',
    genres: ['Drama', 'Anime'],
    posterLabel: 'Nova Tides',
    overview: 'A shoreline colony keeps record of a new star.',
    runtimeLabel: '25m',
  ),
  SearchMediaItem(
    id: 'neon-relay',
    title: 'Neon Relay',
    year: 2025,
    rating: 8.4,
    language: SearchLanguageFilter.japanese,
    mediaType: SearchMediaTypeFilter.anime,
    provider: 'Hulu',
    genres: ['Action', 'Anime'],
    posterLabel: 'Neon Relay',
    overview: 'A relay team races across a neon mountain line.',
    runtimeLabel: '24m',
  ),
  SearchMediaItem(
    id: 'sand-archive',
    title: 'Sand Archive',
    year: 2023,
    rating: 7.2,
    language: SearchLanguageFilter.tamil,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Sun NXT',
    genres: ['Drama'],
    posterLabel: 'Sand Archive',
    overview: 'A curator preserves lost desert recordings.',
    runtimeLabel: '2h 00m',
  ),
  SearchMediaItem(
    id: 'thunder-veil',
    title: 'Thunder Veil',
    year: 2022,
    rating: 7.4,
    language: SearchLanguageFilter.hindi,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Netflix',
    genres: ['Action'],
    posterLabel: 'Thunder Veil',
    overview: 'A covert agent follows a storm-born signal.',
    runtimeLabel: '2h 12m',
  ),
  SearchMediaItem(
    id: 'moon-harbor',
    title: 'Moon Harbor',
    year: 2024,
    rating: 8.0,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Prime Video',
    genres: ['Mystery', 'TV'],
    posterLabel: 'Moon Harbor',
    overview: 'Dock workers uncover a signal beneath the harbor.',
    runtimeLabel: '41m',
  ),
  SearchMediaItem(
    id: 'shatterline',
    title: 'Shatterline',
    year: 2024,
    rating: 7.9,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Crunchyroll',
    genres: ['Drama', 'TV'],
    posterLabel: 'Shatterline',
    overview: 'A fractured city tries to reconnect its transit lines.',
    runtimeLabel: '49m',
  ),
  SearchMediaItem(
    id: 'arcadia-drift',
    title: 'Arcadia Drift',
    year: 2025,
    rating: 7.8,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Plex',
    genres: ['Adventure', 'TV'],
    posterLabel: 'Arcadia Drift',
    overview: 'A drifting station city keeps its balance over the clouds.',
    runtimeLabel: '43m',
  ),
  SearchMediaItem(
    id: 'the-last-circuit',
    title: 'The Last Circuit',
    year: 2024,
    rating: 8.1,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Disney+',
    genres: ['Sci-Fi', 'TV'],
    posterLabel: 'The Last Circuit',
    overview: 'Engineers race to keep the final public grid alive.',
    runtimeLabel: '45m',
  ),
  SearchMediaItem(
    id: 'tamil-rain',
    title: 'Tamil Rain',
    year: 2023,
    rating: 7.1,
    language: SearchLanguageFilter.tamil,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Sun NXT',
    genres: ['Drama'],
    posterLabel: 'Tamil Rain',
    overview: 'A family story unfolds through monsoon seasons.',
    runtimeLabel: '2h 03m',
  ),
  SearchMediaItem(
    id: 'hindi-loom',
    title: 'Hindi Loom',
    year: 2024,
    rating: 7.6,
    language: SearchLanguageFilter.hindi,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Netflix',
    genres: ['Drama', 'TV'],
    posterLabel: 'Hindi Loom',
    overview: 'Textile workers lead a citywide night campaign.',
    runtimeLabel: '36m',
  ),
  SearchMediaItem(
    id: 'korean-run',
    title: 'Korean Run',
    year: 2025,
    rating: 8.3,
    language: SearchLanguageFilter.korean,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Apple TV',
    genres: ['Action'],
    posterLabel: 'Korean Run',
    overview: 'A courier outruns a collapsing supply chain.',
    runtimeLabel: '1h 59m',
  ),
  SearchMediaItem(
    id: 'japan-noir',
    title: 'Japan Noir',
    year: 2024,
    rating: 8.0,
    language: SearchLanguageFilter.japanese,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Crunchyroll',
    genres: ['Thriller'],
    posterLabel: 'Japan Noir',
    overview: 'A detective traces a missing street of memories.',
    runtimeLabel: '2h 01m',
  ),
  SearchMediaItem(
    id: 'chennai-grid',
    title: 'Chennai Grid',
    year: 2025,
    rating: 7.8,
    language: SearchLanguageFilter.tamil,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Sun NXT',
    genres: ['Action', 'TV'],
    posterLabel: 'Chennai Grid',
    overview: 'A maintenance crew keeps a city grid breathing.',
    runtimeLabel: '42m',
  ),
  SearchMediaItem(
    id: 'delhi-broadcast',
    title: 'Delhi Broadcast',
    year: 2022,
    rating: 7.0,
    language: SearchLanguageFilter.hindi,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'YouTube',
    genres: ['Drama'],
    posterLabel: 'Delhi Broadcast',
    overview: 'A local radio host answers calls during a blackout.',
    runtimeLabel: '1h 44m',
  ),
  SearchMediaItem(
    id: 'osaka-signal',
    title: 'Osaka Signal',
    year: 2023,
    rating: 7.9,
    language: SearchLanguageFilter.japanese,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Plex',
    genres: ['Mystery', 'TV'],
    posterLabel: 'Osaka Signal',
    overview: 'A rooftop antenna starts answering the city.',
    runtimeLabel: '46m',
  ),
  SearchMediaItem(
    id: 'seoul-loop',
    title: 'Seoul Loop',
    year: 2025,
    rating: 8.2,
    language: SearchLanguageFilter.korean,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Netflix',
    genres: ['Sci-Fi', 'TV'],
    posterLabel: 'Seoul Loop',
    overview: 'A delivery app reveals repeated city cycles.',
    runtimeLabel: '39m',
  ),
  SearchMediaItem(
    id: 'tokyo-bloom',
    title: 'Tokyo Bloom',
    year: 2024,
    rating: 8.6,
    language: SearchLanguageFilter.japanese,
    mediaType: SearchMediaTypeFilter.anime,
    provider: 'Crunchyroll',
    genres: ['Anime', 'Drama'],
    posterLabel: 'Tokyo Bloom',
    overview: 'A flower market blooms over a subway station.',
    runtimeLabel: '23m',
  ),
  SearchMediaItem(
    id: 'chennai-echo',
    title: 'Chennai Echo',
    year: 2024,
    rating: 7.5,
    language: SearchLanguageFilter.tamil,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Sun NXT',
    genres: ['Thriller'],
    posterLabel: 'Chennai Echo',
    overview: 'A musician decodes messages hidden in street noise.',
    runtimeLabel: '2h 06m',
  ),
  SearchMediaItem(
    id: 'hindi-harbor',
    title: 'Hindi Harbor',
    year: 2023,
    rating: 7.3,
    language: SearchLanguageFilter.hindi,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Prime Video',
    genres: ['Drama', 'TV'],
    posterLabel: 'Hindi Harbor',
    overview: 'A port town negotiates with a changing coastline.',
    runtimeLabel: '40m',
  ),
  SearchMediaItem(
    id: 'korean-night',
    title: 'Korean Night',
    year: 2022,
    rating: 7.4,
    language: SearchLanguageFilter.korean,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Hulu',
    genres: ['Thriller'],
    posterLabel: 'Korean Night',
    overview: 'A courier crosses Seoul with an encrypted case.',
    runtimeLabel: '1h 49m',
  ),
  SearchMediaItem(
    id: 'japanese-rain',
    title: 'Japanese Rain',
    year: 2024,
    rating: 8.1,
    language: SearchLanguageFilter.japanese,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Apple TV',
    genres: ['Drama'],
    posterLabel: 'Japanese Rain',
    overview: 'A city learns how to listen when rain changes its tone.',
    runtimeLabel: '1h 53m',
  ),
  SearchMediaItem(
    id: 'metro-thread',
    title: 'Metro Thread',
    year: 2025,
    rating: 7.9,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Netflix',
    genres: ['Action', 'TV'],
    posterLabel: 'Metro Thread',
    overview: 'Transit workers stitch the city back together each night.',
    runtimeLabel: '44m',
  ),
  SearchMediaItem(
    id: 'orbit-lane',
    title: 'Orbit Lane',
    year: 2024,
    rating: 7.8,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Plex',
    genres: ['Adventure'],
    posterLabel: 'Orbit Lane',
    overview: 'A pilot keeps to a lane no map remembers.',
    runtimeLabel: '1h 42m',
  ),
  SearchMediaItem(
    id: 'aurora-file',
    title: 'Aurora File',
    year: 2026,
    rating: 8.2,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Disney+',
    genres: ['Thriller'],
    posterLabel: 'Aurora File',
    overview: 'Encrypted notes from the north light hide a map.',
    runtimeLabel: '1h 57m',
  ),
  SearchMediaItem(
    id: 'horizon-room',
    title: 'Horizon Room',
    year: 2025,
    rating: 8.0,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Prime Video',
    genres: ['Mystery', 'TV'],
    posterLabel: 'Horizon Room',
    overview: 'An office at the edge of the map sees the future.',
    runtimeLabel: '47m',
  ),
  SearchMediaItem(
    id: 'neon-hall',
    title: 'Neon Hall',
    year: 2023,
    rating: 7.6,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'YouTube',
    genres: ['Drama'],
    posterLabel: 'Neon Hall',
    overview: 'A concert hall keeps a city’s last bright memory.',
    runtimeLabel: '1h 50m',
  ),
  SearchMediaItem(
    id: 'pulse-ward',
    title: 'Pulse Ward',
    year: 2024,
    rating: 8.3,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Hulu',
    genres: ['Drama', 'TV'],
    posterLabel: 'Pulse Ward',
    overview: 'Nurses keep a ward alive when the power goes unstable.',
    runtimeLabel: '41m',
  ),
  SearchMediaItem(
    id: 'signal-archive',
    title: 'Signal Archive',
    year: 2025,
    rating: 8.1,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Netflix',
    genres: ['Sci-Fi'],
    posterLabel: 'Signal Archive',
    overview: 'Archivists catalog transmissions no one can explain.',
    runtimeLabel: '2h 05m',
  ),
  SearchMediaItem(
    id: 'cloud-rail',
    title: 'Cloud Rail',
    year: 2024,
    rating: 7.9,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Apple TV',
    genres: ['Adventure', 'TV'],
    posterLabel: 'Cloud Rail',
    overview: 'A mountain rail line carries cargo through storms.',
    runtimeLabel: '45m',
  ),
  SearchMediaItem(
    id: 'grid-summer',
    title: 'Grid Summer',
    year: 2023,
    rating: 7.4,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Plex',
    genres: ['Drama'],
    posterLabel: 'Grid Summer',
    overview: 'A summer outage changes a neighborhood forever.',
    runtimeLabel: '1h 47m',
  ),
  SearchMediaItem(
    id: 'mirror-code',
    title: 'Mirror Code',
    year: 2025,
    rating: 8.0,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.anime,
    provider: 'Crunchyroll',
    genres: ['Anime', 'Sci-Fi'],
    posterLabel: 'Mirror Code',
    overview: 'A coder finds a second version of their city.',
    runtimeLabel: '24m',
  ),
  SearchMediaItem(
    id: 'harbor-line',
    title: 'Harbor Line',
    year: 2022,
    rating: 7.2,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Disney+',
    genres: ['TV', 'Drama'],
    posterLabel: 'Harbor Line',
    overview: 'Dock crews keep the line alive during storm season.',
    runtimeLabel: '38m',
  ),
  SearchMediaItem(
    id: 'sun-path',
    title: 'Sun Path',
    year: 2024,
    rating: 7.7,
    language: SearchLanguageFilter.tamil,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Sun NXT',
    genres: ['Adventure'],
    posterLabel: 'Sun Path',
    overview: 'Travelers trace a map written in the sun.',
    runtimeLabel: '2h 01m',
  ),
  SearchMediaItem(
    id: 'monsoon-trace',
    title: 'Monsoon Trace',
    year: 2025,
    rating: 7.8,
    language: SearchLanguageFilter.tamil,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Sun NXT',
    genres: ['Drama', 'TV'],
    posterLabel: 'Monsoon Trace',
    overview: 'A weather team follows a storm path across the coast.',
    runtimeLabel: '39m',
  ),
  SearchMediaItem(
    id: 'rain-circuit',
    title: 'Rain Circuit',
    year: 2026,
    rating: 8.0,
    language: SearchLanguageFilter.korean,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'YouTube',
    genres: ['Sci-Fi'],
    posterLabel: 'Rain Circuit',
    overview: 'A technician maps city rain into a circuit board.',
    runtimeLabel: '1h 58m',
  ),
  SearchMediaItem(
    id: 'subway-hush',
    title: 'Subway Hush',
    year: 2024,
    rating: 8.2,
    language: SearchLanguageFilter.korean,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Netflix',
    genres: ['Thriller', 'TV'],
    posterLabel: 'Subway Hush',
    overview: 'Late trains carry secrets under the city.',
    runtimeLabel: '48m',
  ),
  SearchMediaItem(
    id: 'paper-sky',
    title: 'Paper Sky',
    year: 2023,
    rating: 7.9,
    language: SearchLanguageFilter.japanese,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Prime Video',
    genres: ['Drama'],
    posterLabel: 'Paper Sky',
    overview: 'A paper artist builds a sky over a small town.',
    runtimeLabel: '1h 52m',
  ),
  SearchMediaItem(
    id: 'ink-velocity',
    title: 'Ink Velocity',
    year: 2024,
    rating: 8.4,
    language: SearchLanguageFilter.japanese,
    mediaType: SearchMediaTypeFilter.anime,
    provider: 'Crunchyroll',
    genres: ['Anime', 'Action'],
    posterLabel: 'Ink Velocity',
    overview: 'Artists race against a moving ink storm.',
    runtimeLabel: '23m',
  ),
  SearchMediaItem(
    id: 'metro-chant',
    title: 'Metro Chant',
    year: 2025,
    rating: 7.8,
    language: SearchLanguageFilter.hindi,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Netflix',
    genres: ['Music', 'Drama'],
    posterLabel: 'Metro Chant',
    overview: 'A railway choir fights for its rehearsal hall.',
    runtimeLabel: '2h 07m',
  ),
  SearchMediaItem(
    id: 'velvet-route',
    title: 'Velvet Route',
    year: 2024,
    rating: 8.0,
    language: SearchLanguageFilter.korean,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Disney+',
    genres: ['Drama'],
    posterLabel: 'Velvet Route',
    overview: 'A train route unravels a family secret across cities.',
    runtimeLabel: '2h 03m',
  ),
  SearchMediaItem(
    id: 'night-loom',
    title: 'Night Loom',
    year: 2023,
    rating: 7.3,
    language: SearchLanguageFilter.tamil,
    mediaType: SearchMediaTypeFilter.tv,
    provider: 'Hulu',
    genres: ['TV', 'Drama'],
    posterLabel: 'Night Loom',
    overview: 'Weavers keep a harbor town alive after dark.',
    runtimeLabel: '37m',
  ),
  SearchMediaItem(
    id: 'signal-echo',
    title: 'Signal Echo',
    year: 2026,
    rating: 8.5,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'Apple TV',
    genres: ['Thriller', 'Sci-Fi'],
    posterLabel: 'Signal Echo',
    overview: 'Echoes from a tower start answering questions.',
    runtimeLabel: '1h 55m',
  ),
  SearchMediaItem(
    id: 'empty-future',
    title: 'Empty Future',
    year: 2024,
    rating: 7.0,
    language: SearchLanguageFilter.english,
    mediaType: SearchMediaTypeFilter.movie,
    provider: 'YouTube',
    genres: ['Drama'],
    posterLabel: 'Empty Future',
    overview: 'A story about a city that forgot how to fill its streets.',
    runtimeLabel: '1h 39m',
  ),
];
